theme: jekyll-theme-cayman
title: Rock Paper Scissors Lizard Spock
description: Remake of the classic game with GUI and the Lizard Spock expansion
is_user_page: false
is_project_page: true
show_downloads: true